### ISSUE TITLE
Provide deterministic names for exposed `.desktop` files

### ISSUE THREAD

**Issue by TheOneRing** [AppImageCommunity/libappimage#192]
In order to fully integrate with wayland, the app is required to expose the name of its `.desktop` file.
See https://doc.qt.io/qt-6/qguiapplication.html#desktopFileName-prop .
However, at the moment the name is autogenerated.

Here an example generated by https://github.com/TheAssassin/AppImageLauncher
```
~/.local/share/applications/appimagekit_40ac3b334744f726db34885c26868a2e-ownCloud_desktop_sync_client.desktop
~/.local/share/applications/appimagekit_62a6ac994708ae26078a9dffa977e80a-ownCloud_desktop_sync_client.desktop
~/.local/share/applications/appimagekit_babbe5cfada7d3c9d800fc1a657953b6-ownCloud_desktop_sync_client.desktop
```

Please provide the means to retrieve its own `.desktop` file name, for example an environment variable.

Another approach would be that an AppImage can be configured in a way to use the original `.desktop` file name.

**Comment by TheAssassin** [comment]
The specification itself doesn't provide, e.g., an `Environment` key which could be used to make a desktop environment expose that variable to the application. We'd have to implement a custom workaround, e.g., by prepending an `env SOMEVAR=somevalue` to the `Exec` key.

What I could imagine as well is inserting the path of the original AppImage into the desktop file, the specification permits vendor-specific keys. That way, applications could just iterate over all the desktop entries and match the right one. Of course, that doesn't prevent duplicate desktop files, but then again, this should be prevented by the hashing in the first place.

**Comment by TheAssassin** [comment]
Does not seem to be an issue with current versions of Wayland but an issue with the ownCloud desktop client's desktop entry which libappimage then extracts and adapts.

![screenshot_2024-07-23_23-54-19](https://github.com/user-attachments/assets/a0e97a9e-dfc6-449a-8b4f-f483fd1ba7d1)

I just got a fresh copy of KDE Neon, installed AppImageLauncher there and reproduced the issue with the lastest 5.3.1 release. However, adding `StartupWMClass=ownCloud` to the extracted desktop entry fixed the issue, as can be seen in the screenshot. I found this value with `xprop WM_CLASS`.

Please add this key and value to your desktop file and try again, the issue should be gone.

**Comment by TheAssassin** [comment]
Same goes for vanilla Ubuntu 24.04. Before:

![screenshot_2024-07-24_00-35-59](https://github.com/user-attachments/assets/9a1e7dfc-eb67-4d31-a8bc-5838ddcb1129)

After:

![screenshot_2024-07-24_00-36-25](https://github.com/user-attachments/assets/c187cb75-3e86-4e55-ad88-61c9e0c05319)

Closing as "not an issue".

**Comment by TheOneRing** [comment]
Thanks, well give it a try.
